### ISSUE TITLE
create documentation for updating workers

### ISSUE THREAD

**Issue by MalloZup** [kubic-project/automation#513]
# description:

this is followup from  https://github.com/kubic-project/automation/pull/490

We would need a short doc for describing the jenkins/worker internal dependency and update workflow

# tasks:

- [ ]  find a right place for that doc
 
- [ ] create small doc about this minimal info ( where are the workers, how to update things etc) 

- [ ]  send-email to caasp-devel for new doc

**Comment by MalloZup** [comment]
done by @tdaines42
